# Generated by Django 4.2.5 on 2023-12-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='images/profile_photo'),
        ),
    ]
